import { StrategyConfig } from './deployment.types';

export const STRATEGY_CONFIGS: Record<string, StrategyConfig> = {
  rolling: {
    name: 'rolling',
    displayName: 'Rolling Update',
    description: 'Gradual rollout with zero downtime',
    features: [
      'Updates pods one by one',
      'Automatic rollback on failure',
      'Recommended for production',
    ],
    stages: [
      'notify_pods',
      'pod_backup',
      'read_config',
      'pod_hotreload',
      'ready_to_traffic',
      'takes_traffic',
    ],
    icon: 'RefreshCw',
    recommended: true,
    maxUnavailable: 1,
    maxSurge: 1,
    podUpdateDelay: 5000,
    healthCheckDelay: 2000,
  },
  'blue-green': {
    name: 'blue-green',
    displayName: 'Blue-Green Deployment',
    description: 'Complete environment switch',
    features: [
      'Deploy to inactive environment (Green)',
      'Instant traffic switch',
      'Easy rollback to Blue',
    ],
    stages: [
      'notify_pods',
      'pod_backup',
      'read_config_all',
      'pod_hotreload_all',
      'ready_to_traffic_all',
      'switch_traffic',
    ],
    icon: 'GitBranch',
    environmentSwitch: 'instant',
  },
  canary: {
    name: 'canary',
    displayName: 'Canary Deployment',
    description: 'Gradual traffic shifting',
    features: [
      'Start with 10% traffic',
      'Increment to 25%, 50%, 100%',
      'Monitor metrics between stages',
    ],
    stages: [
      'notify_pods',
      'deploy_canary_10',
      'monitor_metrics',
      'deploy_canary_25',
      'monitor_metrics',
      'deploy_canary_50',
      'monitor_metrics',
      'deploy_all_100',
    ],
    icon: 'TrendingUp',
    canaryPercentages: [10, 25, 50, 100],
    metricsWaitTime: 10000,
    podUpdateDelay: 3000,
  },
  recreate: {
    name: 'recreate',
    displayName: 'Recreate',
    description: 'Stop all, then start',
    features: [
      'Downtime expected',
      'Fastest deployment',
      'Use for dev/staging only',
    ],
    stages: [
      'stop_all_pods',
      'notify_pods',
      'read_config_all',
      'start_all_pods',
      'pod_hotreload_all',
      'takes_traffic_all',
    ],
    icon: 'RotateCcw',
    warning: true,
    downtimeExpected: true,
  },
};

export const STAGE_DISPLAY_NAMES: Record<string, string> = {
  notify_pods: 'Notify Pods',
  pod_backup: 'Pod Backup',
  read_config: 'Read Configuration',
  read_config_all: 'Read Configuration (All)',
  pod_hotreload: 'Pod Hotreload',
  pod_hotreload_all: 'Pod Hotreload (All)',
  ready_to_traffic: 'Ready to Take Traffic',
  ready_to_traffic_all: 'Ready to Take Traffic (All)',
  takes_traffic: 'Takes Traffic',
  takes_traffic_all: 'Takes Traffic (All)',
  stop_all_pods: 'Stop All Pods',
  start_all_pods: 'Start All Pods',
  deploy_canary_10: 'Deploy 10% Canary',
  deploy_canary_25: 'Deploy 25% Canary',
  deploy_canary_50: 'Deploy 50% Canary',
  deploy_all_100: 'Deploy Remaining (100%)',
  monitor_metrics: 'Monitor Metrics',
  switch_traffic: 'Switch Traffic',
};
